"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# --------------- AZURE ---------------
# SECRET_KEY = os.getenv('SECRET_KEY')
# DEBUG = os.getenv('DEBUG', '0').lower() in ['true', 't', '1']
# ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS').split(' ')
# CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS').split(' ')
# SECURE_SSL_REDIRECT = \
#     os.getenv('SECURE_SSL_REDIRECT', '0').lower() in ['true', 't', '1']
# if SECURE_SSL_REDIRECT:
#     SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# SESSION_COOKIE_SECURE = True


# --------------- LOCAL ---------------
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ukaam=kjp((te10znbi1tb-#cuhb(0nb+9u6$js8qa4b#-nh^g'
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'members',
    'bootstrap5',
    'storages'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

#STORAGES = {
#    "default": {
#        "BACKEND": "storages.backends.azure_storage.AzureStorage",
#        "OPTIONS": {
#        },
#    },
#}

# ----- Azure Storage settings -----
DEFAULT_FILE_STORAGE = 'project.azure_storage.AzureMediaStorage'
#STATICFILES_STORAGE = 'project.azure_storage.AzureStaticStorage'

AZURE_ACCOUNT_NAME = os.getenv('AZURE_ACCOUNT_NAME')
AZURE_ACCOUNT_KEY = os.getenv('AZURE_ACCOUNT_KEY')
AZURE_CUSTOM_DOMAIN = f'{AZURE_ACCOUNT_NAME}.blob.core.windows.net'

#STATIC_URL = f'https://{AZURE_CUSTOM_DOMAIN}/static/'
#STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = f'https://{AZURE_CUSTOM_DOMAIN}/media/'
MEDIA_ROOT = BASE_DIR / 'mediafiles'

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases


DATABASES = {
    'default': {
         'NAME': 'SideBar_data',
         'ENGINE': 'django.db.backends.sqlite3',
         'USER': '',
         'PASSWORD': '',
    },
    'FIP': {
        'ENGINE': 'mssql',
        #'NAME': os.environ.get('DBNAME'),
        #'HOST': os.environ.get('DBHOST'),
        #'USER': os.environ.get('DBUSER'),
        #'PASSWORD': os.environ.get('DBPASS'),
        'NAME': 'FIP_SLWK',
        'HOST': 'SLWFILEDB.SLWIP.COM',
        'USER': 'SLWKUSER',
        'PASSWORD': 'slwkuser',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            #"extra_params": 'Encrypt=yes;TrustServerCertificate=yes;Connection Timeout=30;',
        },
    } ,
    'SideBar': {
        'NAME': 'SideBar_data',
        'ENGINE': 'django.db.backends.sqlite3',
        'USER': '',
        'PASSWORD': '',
    },
}

# TEST ---- django-outlook-email-backend
#OUTLOOK_CREDENTIALS = {
#    'OUTLOOK_CLIENT_ID': 'your-client-id',
#    'OUTLOOK_CLIENT_SECRET': 'your-client-secret',
#    'OUTLOOK_TENANT_ID': 'your-tenant-id',
#}
#EMAIL_BACKEND = 'django_outlook_email.django_outlook_email_backend.OutlookEmailBackend'

# TEST ---- msal for email merges
#CLIENT_ID = os.getenv('MICROSOFT_PROVIDER_CLIENT_ID')
#CLIENT_SECRET = os.getenv('MICROSOFT_PROVIDER_AUTHENTICATION_SECRET')
#TENANT_ID = os.getenv('TENANT_ID')
#AUTHORITY = f'https://login.microsoftonline.com/faf1d7d5-3374-4da3-9836-b7765bc44ef9'
#REDIRECT_URI = f'http://localhost:8000/callback'

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#DATABASE_ROUTERS = ['router.db_routers.AuthRouter',]
'''
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'handlers': {
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
        },
    },
    'loggers': {
        'django.request': {
            'handlers': ['mail_admins'],
            'level': 'ERROR',
            'propagate': True,
        },
        'SideBar': {
            'handlers': ['sidebarlogfile'],
            'level': 'DEBUG',
        },
    },
    'applogfile': {
        'level': 'DEBUG',
        'class': 'logging.handlers.RotatingFileHandler',
        'filename': 'SideBar.log',  # Adjust the path and filename
        'maxBytes': 1024 * 1024 * 15,  # 15MB
        'backupCount': 10,
    }
}
'''
