# Generated by Django 5.0.6 on 2024-05-24 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Matters',
        ),
        migrations.DeleteModel(
            name='Merges',
        ),
    ]
