# Generated by Django 5.0.6 on 2024-06-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergeCategory',
            fields=[
                ('categoryid', models.AutoField(primary_key=True, serialize=False)),
                ('categoryname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'merge_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MergeRole',
            fields=[
                ('roleid', models.AutoField(primary_key=True, serialize=False)),
                ('rolename', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'merge_role',
                'managed': False,
            },
        ),
    ]
